default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: pgcrypto
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  database: <%= ENV['DB_DATABASE'] %>
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  database: sdk_prototype_prod
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
